[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "qudi-core-him"
version = "0.1.0"
description = "Custom qudi-core modules for Nollmann lab setups"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "qudi-core"
]

[project.optional-dependencies]
dev-lint-format = ["ruff==0.7.0"]

[project.urls]
Homepage = "https://github.com/NollmannLab/qudi_core_cbs"
Documentation = "https://github.com/NollmannLab/qudi_core_cbs/docs"
Repository = "https://github.com/NollmannLab/qudi_core_cbs.git"
Changelog = "https://github.com/NollmannLab/qudi_core_cbs/docs/changelog.md"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["qudi*"]